# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AppView = QtWidgets.QTabWidget(self.centralwidget)
        self.AppView.setGeometry(QtCore.QRect(0, -50, 791, 631))
        self.AppView.setObjectName("AppView")
        self.SettingTimer = QtWidgets.QWidget()
        self.SettingTimer.setObjectName("SettingTimer")
        self.pushButton = QtWidgets.QPushButton(self.SettingTimer)
        self.pushButton.setGeometry(QtCore.QRect(330, 430, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.SettingTimer)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 430, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.SettingTimer)
        self.graphicsView.setGeometry(QtCore.QRect(-5, 1, 811, 591))
        self.graphicsView.setObjectName("graphicsView")
        self.timeEdit = QtWidgets.QTimeEdit(self.SettingTimer)
        self.timeEdit.setGeometry(QtCore.QRect(130, 160, 511, 221))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit.setFont(font)
        self.timeEdit.setMaximumTime(QtCore.QTime(10, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.graphicsView.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.timeEdit.raise_()
        self.AppView.addTab(self.SettingTimer, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(-20, -20, 821, 631))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.AppView.addTab(self.tab, "")
        self.TimerView = QtWidgets.QWidget()
        self.TimerView.setObjectName("TimerView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.TimerView)
        self.graphicsView_2.setGeometry(QtCore.QRect(-10, 20, 811, 571))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.TimerView)
        self.timeEdit_2.setGeometry(QtCore.QRect(170, 140, 511, 221))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setReadOnly(True)
        self.timeEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.timeEdit_2.setMaximumTime(QtCore.QTime(10, 0, 0))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.TimerView)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 430, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.TimerView)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 430, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.TimerView)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 430, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.TimerView)
        self.pushButton_6.setGeometry(QtCore.QRect(670, 430, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.AppView.addTab(self.TimerView, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.AppView.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.AppView.setTabText(self.AppView.indexOf(self.SettingTimer), _translate("MainWindow", "Tab 1"))
        self.AppView.setTabText(self.AppView.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.AppView.setTabText(self.AppView.indexOf(self.TimerView), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
