# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AppView = QtWidgets.QTabWidget(self.centralwidget)
        self.AppView.setGeometry(QtCore.QRect(0, -50, 791, 631))
        self.AppView.setObjectName("AppView")
        self.SettingTimer = QtWidgets.QWidget()
        self.SettingTimer.setObjectName("SettingTimer")
        self.StartTimer = QtWidgets.QPushButton(self.SettingTimer)
        self.StartTimer.setGeometry(QtCore.QRect(330, 430, 93, 28))
        self.StartTimer.setObjectName("StartTimer")
        self.ResetTimer = QtWidgets.QPushButton(self.SettingTimer)
        self.ResetTimer.setGeometry(QtCore.QRect(560, 430, 93, 28))
        self.button__ = "pushButton_2"
        self.ResetTimer.setObjectName("%s" % self.button__)
        self.graphicsView = QtWidgets.QGraphicsView(self.SettingTimer)
        self.graphicsView.setGeometry(QtCore.QRect(-5, 1, 811, 591))
        self.graphicsView.setObjectName("GraphicsView")
        self.timeEdit = QtWidgets.QTimeEdit(self.SettingTimer)
        self.timeEdit.setGeometry(QtCore.QRect(130, 160, 511, 221))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit.setFont(font)
        self.timeEdit.setMaximumTime(QtCore.QTime(10, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        # self.graphicsView.raise_()
        self.StartTimer.raise_()
        self.ResetTimer.raise_()
        self.timeEdit.raise_()
        self.AppView.addTab(self.SettingTimer, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(-20, -20, 821, 631))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.AppView.addTab(self.tab, "")
        self.TimerView = QtWidgets.QWidget()
        self.TimerView.setObjectName("TimerView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.TimerView)
        self.graphicsView_2.setGeometry(QtCore.QRect(-10, 20, 811, 571))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.TimerView)
        self.timeEdit_2.setGeometry(QtCore.QRect(170, 140, 511, 221))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setReadOnly(True)
        self.timeEdit_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.timeEdit_2.setMaximumTime(QtCore.QTime(10, 0, 0))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.PauseTimer = QtWidgets.QPushButton(self.TimerView)
        self.PauseTimer.setGeometry(QtCore.QRect(100, 430, 100, 28))
        self.PauseTimer.setObjectName("PauseTimer")
        self.ContinueTimer = QtWidgets.QPushButton(self.TimerView)
        self.ContinueTimer.setGeometry(QtCore.QRect(300, 430, 100, 28))
        self.ContinueTimer.setObjectName("ContinueTimer")
        self.ResetTimer_2 = QtWidgets.QPushButton(self.TimerView)
        self.ResetTimer_2.setGeometry(QtCore.QRect(510, 430, 100, 28))
        self.ResetTimer_2.setObjectName("ResetTimer")
        self.CancelTimer= QtWidgets.QPushButton(self.TimerView)
        self.CancelTimer.setGeometry(QtCore.QRect(670, 430, 100, 28))
        self.CancelTimer.setObjectName("CancelTimer")
        self.AppView.addTab(self.TimerView, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.AppView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartTimer.setText(_translate("MainWindow", "Start Timer"))
        self.ResetTimer.setText(_translate("MainWindow", "Reset Timer"))
        self.AppView.setTabText(self.AppView.indexOf(self.SettingTimer), _translate("MainWindow", "Tab 1"))
        self.AppView.setTabText(self.AppView.indexOf(self.tab), _translate("MainWindow", "Page"))
        self.PauseTimer.setText(_translate("MainWindow", "Pause Timer"))
        self.ContinueTimer.setText(_translate("MainWindow", "Continue Timer"))
        self.ResetTimer_2.setText(_translate("MainWindow", "Reset Timer"))
        self.CancelTimer.setText(_translate("MainWindow", "Cancel Timer"))
        self.AppView.setTabText(self.AppView.indexOf(self.TimerView), _translate("MainWindow", "Tab 2"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
